language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - yarn lint
cache:
  yarn: true
  directories:
    - node_modules
